### ISSUE TITLE
 Can't find a codec for class org.apache.camel.impl.DefaultExchangeHolder.: Can't find a codec for class org.apache.camel.impl.DefaultExchangeHolder

### ISSUE THREAD

**Issue by anujitas** [seleniumkit/selenograph#17]
Versions ;
Ubuntu : 14.04
Selenograph : 1.2-1
Mongod : 3.4.4

I have designed my test.xml file and the same is reflected on selenograph UI on the specified port (4444). When I start the service of yandex-selenograph , it shows that that the service is connected to the given port but eventually lands up into the above mentioned error. 

I have libmongo-client0-dbg package installed (alternate for mongo driver) but not working  :(
Also looked for bson installation and mongodb java driver & mongodb- java-driver-core ; still not working 

I also get the below error :+1: 
 ERROR CamelotAggregationStrategy - Repository failure occurred, SKIPPING MESSAGE for plugin 'quotaStats' with key 'all'
Caused by ru.yandex.qatools.camelot.api.error.RepositoryFailureException: Failed to get exchange for key 'all': Failed to get exchange for key 'all'
ERROR MongodbAggregationRepository - [quotaStats] Failed to update map for key 'all'
Caused by org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class org.apache.camel.impl.DefaultExchangeHolder.: Can't find a codec for class org.apache.camel.impl.DefaultExchangeHolder.

Is there any dependency package I am missing or any version compatibility issue? Please specify.

**Comment by vania-pooh** [comment]
@Infobeans-Anujita I have bad and good news for you. The bad news - this project is deprecated and nobody maintains it. Good news - there is an active community with the next generation Selenium cluster projects from the same team here: https://github.com/aerokube Take a look at the website: http://aerokube.com/ - here you will find links to projects and articles to be read.
